# tokage tests configuration for sample codes

# 単調増加チェックのテスト
[[tests]]
name = "Monotonic Check - Strictly Increasing"
command = "bash"
args = ["-c", "cd ../sample_code && cargo build --quiet && ./target/debug/sample_code"]
input = """3
1 2 5
"""
expected_output = "Yes"
timeout_secs = 5

[[tests]]
name = "Monotonic Check - Not Strictly Increasing"
command = "bash"
args = ["-c", "cd ../sample_code && cargo build --quiet && ./target/debug/sample_code"]
input = """3
3 9 5
"""
expected_output = "No"
timeout_secs = 5

[[tests]]
name = "Monotonic Check - Equal Values"
command = "bash"
args = ["-c", "cd ../sample_code && cargo build --quiet && ./target/debug/sample_code"]
input = """4
1 2 2 3
"""
expected_output = "No"
timeout_secs = 5

# 偶数カウンターのテスト
[[tests]]
name = "Even Counter - Some Even Numbers"
command = "bash"
args = ["-c", "cd ../even_counter && cargo build --quiet && ./target/debug/even_counter"]
input = """5
1 2 3 4 5
"""
expected_output = "2"
timeout_secs = 5

[[tests]]
name = "Even Counter - All Even Numbers"
command = "bash"
args = ["-c", "cd ../even_counter && cargo build --quiet && ./target/debug/even_counter"]
input = """3
2 4 6
"""
expected_output = "3"
timeout_secs = 5

[[tests]]
name = "Even Counter - No Even Numbers"
command = "bash"
args = ["-c", "cd ../even_counter && cargo build --quiet && ./target/debug/even_counter"]
input = """4
1 3 5 7
"""
expected_output = "0"
timeout_secs = 5

# 最大値を求めるテスト
[[tests]]
name = "Max Finder - Positive Numbers"
command = "bash"
args = ["-c", "cd ../max_finder && cargo build --quiet && ./target/debug/max_finder"]
input = """5
1 3 5 2 4
"""
expected_output = "5"
timeout_secs = 5

[[tests]]
name = "Max Finder - Negative Numbers"
command = "bash"
args = ["-c", "cd ../max_finder && cargo build --quiet && ./target/debug/max_finder"]
input = """3
-1 -5 -3
"""
expected_output = "-1"
timeout_secs = 5

[[tests]]
name = "Max Finder - Mixed Numbers"
command = "bash"
args = ["-c", "cd ../max_finder && cargo build --quiet && ./target/debug/max_finder"]
input = """4
-2 0 3 -1
"""
expected_output = "3"
timeout_secs = 5 