# templates/modsecurity-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: modsecurity-config
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
data:
  custom-modsecurity.conf: |-
{{ .Files.Get "modsecurity/custom-modsecurity.conf" | indent 4 }}
